### ISSUE TITLE
kthresher: Uses Package.section, incompatible with python-apt 1.9

### ISSUE THREAD

**Issue by jkirk** [rackerlabs/kthresher#80]
Julian Andres Klode reported in [Debian-Bug #931024](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931024):

> According to codesearch.d.n, kthresher contains trhe line:
> 
>             "kernel" in pkg.section and re.match(kernel_image_regex, pkg_name)
> 
> The use of the section on packages has been deprecated ages ago, as
> it can vary between versions. 
> 
> This causes kthresher to stop working with apt 1.9, so please migrate to
> using a version's section after the buster release.

See: https://github.com/rackerlabs/kthresher/blob/0930ab9561c0062700fc5e7b9898687eea8add66/kthresher.py#L275

**Comment by tonyskapunk** [comment]
Property `section` was deprecated and fully removed from `apt` **1.9** that likely will be shipped with Debian [buster](https://wiki.debian.org/DebianBuster) , commit https://salsa.debian.org/apt-team/python-apt/commit/cbca484748983a4fff5f884177237bf556c357b6 made it into [experimental]( https://packages.debian.org/source/experimental/python-apt) and causes `kthresher` to fail:

```
AttributeError: 'Package' object has no attribute 'section'
```

`section` was moved into `Version` class and is suggested to get it from there instead.

**Comment by tonyskapunk** [comment]
Fixed in #81
